---
- name: CIS v1.11 Self Assessment Playbook
  hosts: all
  become: true
  gather_facts: true
  vars_prompt:
    - name: reports_dir
      prompt: Enter directory to save reports (default current working dir)
      private: false
      default: reports
  tasks:
    - name: Run Pre Audit
      ansible.builtin.import_role:
        name: pre_audit

    - name: Run CIS v1.11 Self Assessment
      ansible.builtin.import_role:
        name: cis_self_assessment111
